## model
model_name_or_path:  saves/Qwen2.5-Coder-7B/PT/full/train_2024-12-26-21-30-00

## output
output_dir: saves/Qwen2.5-Coder-7B/SFT/full/train_2024-12-26-21-30-00
logging_steps: 1
save_steps: 20
plot_loss: true
report_to: all
include_num_input_tokens_seen: true
save_total_limit: 1
load_best_model_at_end: true  # 在训练结束时加载最佳模型
metric_for_best_model: "eval_loss"  # 使用eval_loss作为选择最佳模型的指标

## method
stage: sft
do_train: true
finetuning_type: full
template: qwen
flash_attn: fa2
### badam
use_badam: true
badam_mode: layer
badam_switch_mode: ascending
badam_switch_interval: 10
badam_update_ratio: 0.05

## dataset
dataset_dir: /home/clouder/ose_code_model_data_preprocess/train
dataset: ose_sft
cutoff_len: 4096

### train
learning_rate: 2.0e-05
num_train_epochs: 3.0
max_samples: 100000
preprocessing_num_workers: 16
overwrite_cache: true
per_device_train_batch_size: 2
gradient_accumulation_steps: 64
lr_scheduler_type: cosine
max_grad_norm: 1.0
warmup_steps: 0
optim: adamw_torch
packing: false
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
eval_strategy: steps    # 每隔一定步数进行评估
eval_steps: 5           # 每5步进行一次评估
per_device_eval_batch_size: 2 


