bf16: true
cutoff_len: 4096
dataset: ose_data
dataset_dir: /home/clouder/ose_code_model_data_preprocess/train
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 16
include_num_input_tokens_seen: true
learning_rate: 1.0e-05
logging_steps: 2
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /home/clouder/.xinference/cache/codeqwen1.5-2-pytorch-7b
num_train_epochs: 1.0
optim: adamw_torch
output_dir: /tmp/saves/Qwen1.5-Code-7B/lora/train_xxx
packing: true
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
report_to: all
save_steps: 100
stage: pt
template: default
use_unsloth: true
warmup_steps: 0
